# Generated by Django 2.0.6 on 2018-07-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180711_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Categoty',
            new_name='categoty',
        ),
    ]
