# Generated by Django 2.0.6 on 2018-07-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180714_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='categoty',
            new_name='category',
        ),
    ]
