# Generated by Django 2.0.6 on 2018-07-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20180714_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='matching',
            field=models.BooleanField(),
        ),
    ]
